name: sm
channels:
  - menpo
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - atk-1.0=2.38.0
  - attr=2.5.1
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2024.12.14
  - cairo=1.18.2
  - elfutils=0.190
  - file=5.46
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.12
  - gnutls=3.8.8
  - graphite2=1.3.13
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=10.1.0
  - icu=75.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libarchive=3.7.7
  - libcap=2.69
  - libcurl=8.11.1
  - libdb=6.2.32
  - libdeflate=1.23
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt=1.11.0
  - libgcrypt-devel=1.11.0
  - libgcrypt-lib=1.11.0
  - libgcrypt-tools=1.11.0
  - libgd=2.3.3
  - libglib=2.82.2
  - libgomp=14.2.0
  - libgpg-error=1.51
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=3.0.0
  - liblzma=5.6.3
  - libmagic=5.46
  - libmicrohttpd=1.0.1
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libpng=1.6.44
  - librsvg=2.58.4
  - libsqlite=3.45.2
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.5
  - libzlib=1.3.1
  - lmdb=0.9.31
  - lua=5.4.6
  - lz4-c=1.10.0
  - lzo=2.10
  - ncurses=6.4
  - nettle=3.9.1
  - nspr=4.35
  - nss=3.98
  - openssl=3.4.0
  - osmesa=12.2.2.dev
  - p11-kit=0.24.1
  - pango=1.54.0
  - patchelf=0.17.2
  - pcre2=10.44
  - pip=24.2
  - pixman=0.44.2
  - popt=1.19
  - pthread-stubs=0.4
  - python=3.8.18
  - python_abi=3.8
  - readline=8.2
  - rpm-tools=4.17.1
  - setuptools=75.1.0
  - spot=2.12
  - sqlite=3.45.2
  - tk=8.6.13
  - wheel=0.44.0
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xz=5.4.6
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - annotated-types==0.7.0
      - cachetools==5.5.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - click==8.1.8
      - cloudpickle==3.0.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==0.29.37
      - docker-pycreds==0.4.0
      - etils==1.3.0
      - eval-type-backport==0.2.2
      - farama-notifications==0.0.4
      - fasteners==0.19
      - filelock==3.15.4
      - fonttools==4.53.1
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - glfw==2.7.0
      - google-auth==2.34.0
      - google-auth-oauthlib==1.0.0
      - graphviz==0.20.3
      - grpcio==1.66.1
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==0.28.1
      - gymnasium-robotics==1.3.1
      - highway-env==1.9.1
      - idna==3.8
      - imageio==2.35.0
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==8.2.0
      - importlib-resources==6.4.0
      - jax-jumpy==1.0.0
      - jinja2==3.1.4
      - joblib==0.14.1
      - kiwisolver==1.4.5
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mpmath==1.3.0
      - mujoco==3.1.6
      - mujoco-py==2.1.2.14
      - networkx==3.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.20
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - opencv-python==4.10.0.84
      - packaging==24.1
      - pandas==2.0.3
      - pettingzoo==1.24.3
      - pillow==10.4.0
      - platformdirs==4.3.6
      - protobuf==4.25.3
      - psutil==6.0.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygame==2.1.0
      - pyopengl==3.1.10
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.2
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - scipy==1.10.1
      - seaborn==0.13.2
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - six==1.16.0
      - smmap==5.0.2
      - stable-baselines3==2.0.0
      - sympy==1.13.2
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - torch==2.4.1
      - triton==3.0.0
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - wandb==0.19.7
      - werkzeug==3.0.4
      - xmltodict==0.13.0
      - zipp==3.20.0
prefix: /home/geraudnt/miniconda3/envs/sm
